[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "Arpd64riUqFBhUBmLrgAJiS7bnkJzqPB4NZaKnYCXKxX"

[programs.devnet]
counter = "Arpd64riUqFBhUBmLrgAJiS7bnkJzqPB4NZaKnYCXKxX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/aadilahmed/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
